name: build

on:
  workflow_dispatch:
    inputs:
      commitHash:
        description: 'webrtc-sdk commit hash'
        default: ''
        required: true
      configuration:
        description: 'build configuration'
        default: 'release'
        required: true
        type: choice
        options:
          - release
          - debug
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
      - '.gitignore'
      - '.dockerignore'
    branches-ignore:
      - daily
    tags:
      - '*'

permissions:
  packages: write
  contents: write
  actions: read

jobs:
  build-apple:
    defaults:
      run:
        working-directory: ./build
    strategy:
      fail-fast: false
      matrix:
        name:
          - apple
          - apple_prefixed
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v5
    - name: Select Xcode 26.0
      run: sudo xcode-select --switch /Applications/Xcode_26.0.app/Contents/Developer
    - name: Build
      id: build
      run: ./build.${{ matrix.name }}.sh "${{ github.event.inputs.commitHash }}" "${{ github.event.inputs.configuration || 'release' }}"
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.build.outputs.framework_name }}.xcframework.zip
        path: build/_package/${{ matrix.name }}/${{ steps.build.outputs.framework_name }}.xcframework.zip
  build-linux:
    defaults:
      run:
        working-directory: ./build
    strategy:
      fail-fast: false
      matrix:
        name:
          - android
          - android_prefixed
          - android_prefixed_stripped
    runs-on: nscloud-ubuntu-22.04-amd64-8x16
    steps:
    - uses: actions/checkout@v4
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
      with:
        android: false
        tool-cache: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
    - run: ./build.${{ matrix.name }}.sh "${{ github.event.inputs.commitHash }}"
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: webrtc.${{ matrix.name }}.tar.gz
        path: build/_package/${{ matrix.name }}/webrtc.tar.gz
  create-release:
    name: Create Release
    if: github.ref_type == 'tag'
    needs:
      - build-apple
      - build-linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        path: artifacts
        name: webrtc.android_prefixed.tar.gz
    - uses: actions/download-artifact@v4
      with:
        path: artifacts
        name: webrtc.android_prefixed_stripped.tar.gz
    - uses: actions/download-artifact@v4
      with:
        path: artifacts
        name: LiveKitWebRTC.xcframework.zip
    - uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: artifacts/**
